/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import gerenciamento.GerenciamentoHospitalar;
import javax.swing.JOptionPane;

/**
 *
 * @author Amanda
 */
public class TelaInicialAdministrador extends javax.swing.JFrame {

    GerenciamentoHospitalar admHospital = new GerenciamentoHospitalar();
    /**
     * Creates new form TelaAdministrador
     */
    public TelaInicialAdministrador(GerenciamentoHospitalar admHospital) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.admHospital = admHospital;
        admHospital.getLeitos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        infoAdm = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();
        gerenciar = new javax.swing.JMenu();
        leitos = new javax.swing.JMenu();
        cadastrarLeito = new javax.swing.JMenuItem();
        alterarLeito = new javax.swing.JMenuItem();
        alterarStatus = new javax.swing.JMenuItem();
        verificarLeitos = new javax.swing.JMenuItem();
        suprimentos = new javax.swing.JMenu();
        novoSuprimento = new javax.swing.JMenuItem();
        alterarEstoque = new javax.swing.JMenuItem();
        verificarSuprimentos = new javax.swing.JMenuItem();
        internacoes = new javax.swing.JMenu();
        verificarInternacoes = new javax.swing.JMenuItem();
        pacientes = new javax.swing.JMenu();
        solicitacoesCadastro = new javax.swing.JMenuItem();
        verificarPacientes = new javax.swing.JMenuItem();
        recursosHumanos = new javax.swing.JMenu();
        medicos = new javax.swing.JMenu();
        novoMedico = new javax.swing.JMenuItem();
        alterarDadosMedico = new javax.swing.JMenuItem();
        listaMedicos = new javax.swing.JMenuItem();
        buscarMedicos = new javax.swing.JMenu();
        especialidadeMedico = new javax.swing.JMenuItem();
        dataAdmissaoMedico = new javax.swing.JMenuItem();
        enfermeiros = new javax.swing.JMenu();
        novoEnfermeiro = new javax.swing.JMenuItem();
        alterarDadosEnfermeiro = new javax.swing.JMenuItem();
        listaEnfermeiros = new javax.swing.JMenuItem();
        tecnicos = new javax.swing.JMenu();
        novoTecnico = new javax.swing.JMenuItem();
        alterarDadosTecnico = new javax.swing.JMenuItem();
        listaTecnicos = new javax.swing.JMenuItem();
        farmaceuticos = new javax.swing.JMenu();
        novoFarmaceutico = new javax.swing.JMenuItem();
        alterarDadosFarmaceutico = new javax.swing.JMenuItem();
        listaFarmaceuticos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Geral");

        infoAdm.setText("Informações Administrativas");
        infoAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoAdmActionPerformed(evt);
            }
        });
        jMenu1.add(infoAdm);

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu1.add(sair);

        jMenuBar1.add(jMenu1);

        gerenciar.setText("Gerenciamento Hospitalar");

        leitos.setText("Leitos");

        cadastrarLeito.setText("Cadastrar");
        cadastrarLeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLeitoActionPerformed(evt);
            }
        });
        leitos.add(cadastrarLeito);

        alterarLeito.setText("Alterar");
        leitos.add(alterarLeito);

        alterarStatus.setText("Alterar Status");
        alterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarStatusActionPerformed(evt);
            }
        });
        leitos.add(alterarStatus);

        verificarLeitos.setText("Verificar Leitos");
        verificarLeitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarLeitosActionPerformed(evt);
            }
        });
        leitos.add(verificarLeitos);

        gerenciar.add(leitos);

        suprimentos.setText("Suprimentos");

        novoSuprimento.setText("Novo Suprimento");
        novoSuprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoSuprimentoActionPerformed(evt);
            }
        });
        suprimentos.add(novoSuprimento);

        alterarEstoque.setText("Alterar Estoque");
        alterarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEstoqueActionPerformed(evt);
            }
        });
        suprimentos.add(alterarEstoque);

        verificarSuprimentos.setText("Verificar Suprimentos");
        suprimentos.add(verificarSuprimentos);

        gerenciar.add(suprimentos);

        internacoes.setText("Internações");

        verificarInternacoes.setText("Verificar Internações");
        internacoes.add(verificarInternacoes);

        gerenciar.add(internacoes);

        pacientes.setText("Pacientes");

        solicitacoesCadastro.setText("Solicitações de Cadastro");
        solicitacoesCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitacoesCadastroActionPerformed(evt);
            }
        });
        pacientes.add(solicitacoesCadastro);

        verificarPacientes.setText("Verificar Pacientes");
        pacientes.add(verificarPacientes);

        gerenciar.add(pacientes);

        jMenuBar1.add(gerenciar);

        recursosHumanos.setText("Recursos Humanos");

        medicos.setText("Médicos");

        novoMedico.setText("Novo Médico");
        novoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoMedicoActionPerformed(evt);
            }
        });
        medicos.add(novoMedico);

        alterarDadosMedico.setText("Alterar Dados do Médico");
        medicos.add(alterarDadosMedico);

        listaMedicos.setText("Lista de Médicos");
        listaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMedicosActionPerformed(evt);
            }
        });
        medicos.add(listaMedicos);

        buscarMedicos.setText("Buscar Médicos");

        especialidadeMedico.setText("Por Especialidade");
        buscarMedicos.add(especialidadeMedico);

        dataAdmissaoMedico.setText("Por Data de Admisssão");
        dataAdmissaoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAdmissaoMedicoActionPerformed(evt);
            }
        });
        buscarMedicos.add(dataAdmissaoMedico);

        medicos.add(buscarMedicos);

        recursosHumanos.add(medicos);

        enfermeiros.setText("Enfermeiros");

        novoEnfermeiro.setText("Novo Enfermeiro");
        novoEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoEnfermeiroActionPerformed(evt);
            }
        });
        enfermeiros.add(novoEnfermeiro);

        alterarDadosEnfermeiro.setText("Alterar Dados do Enfermeiro");
        enfermeiros.add(alterarDadosEnfermeiro);

        listaEnfermeiros.setText("Lista de Enfermeiros");
        listaEnfermeiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaEnfermeirosActionPerformed(evt);
            }
        });
        enfermeiros.add(listaEnfermeiros);

        recursosHumanos.add(enfermeiros);

        tecnicos.setText("Técnicos de Enfermagem");

        novoTecnico.setText("Novo Técnico");
        novoTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoTecnicoActionPerformed(evt);
            }
        });
        tecnicos.add(novoTecnico);

        alterarDadosTecnico.setText("Alterar Dados do Técnico");
        tecnicos.add(alterarDadosTecnico);

        listaTecnicos.setText("Lista de Técnicos");
        listaTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaTecnicosActionPerformed(evt);
            }
        });
        tecnicos.add(listaTecnicos);

        recursosHumanos.add(tecnicos);

        farmaceuticos.setText("Farmacêuticos");

        novoFarmaceutico.setText("Novo Farmacêutico");
        novoFarmaceutico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoFarmaceuticoActionPerformed(evt);
            }
        });
        farmaceuticos.add(novoFarmaceutico);

        alterarDadosFarmaceutico.setText("Alterar Dados do Farmacêutico");
        farmaceuticos.add(alterarDadosFarmaceutico);

        listaFarmaceuticos.setText("Lista de Farmacêuticos");
        listaFarmaceuticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaFarmaceuticosActionPerformed(evt);
            }
        });
        farmaceuticos.add(listaFarmaceuticos);

        recursosHumanos.add(farmaceuticos);

        jMenuBar1.add(recursosHumanos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sairMouseClicked

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void alterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarStatusActionPerformed

    private void novoSuprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoSuprimentoActionPerformed
        // TODO add your handling code here:
        new TelaCadastroSuprimento(admHospital).setVisible(true);
        dispose();
    }//GEN-LAST:event_novoSuprimentoActionPerformed

    private void alterarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarEstoqueActionPerformed

    private void dataAdmissaoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAdmissaoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAdmissaoMedicoActionPerformed

    private void cadastrarLeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLeitoActionPerformed
        // TODO add your handling code here:
        new TelaCadastroLeito(admHospital).setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarLeitoActionPerformed

    private void verificarLeitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarLeitosActionPerformed
        // TODO add your handling code here:
        if(admHospital.getLeitos().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum Leito Cadastrado!");
        } else {
            new TelaListaLeitos(admHospital).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_verificarLeitosActionPerformed

    private void novoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoMedicoActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarPessoa(admHospital, 1).setVisible(true);
        dispose();
    }//GEN-LAST:event_novoMedicoActionPerformed

    private void listaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMedicosActionPerformed
        // TODO add your handling code here:
        if(admHospital.getMedicos().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum Médico Cadastrado!");
        } else {
            new TelaListaMedicos(admHospital).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_listaMedicosActionPerformed

    private void novoEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoEnfermeiroActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarPessoa(admHospital, 2).setVisible(true);
        dispose();
    }//GEN-LAST:event_novoEnfermeiroActionPerformed

    private void listaEnfermeirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaEnfermeirosActionPerformed
        // TODO add your handling code here:
        if(admHospital.getEnfermeiros().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum Enfermeiro Cadastrado!");
        } else {
            new TelaListaEnfermeiros(admHospital).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_listaEnfermeirosActionPerformed

    private void novoTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoTecnicoActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarPessoa(admHospital, 3).setVisible(true);
        dispose();
    }//GEN-LAST:event_novoTecnicoActionPerformed

    private void listaTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaTecnicosActionPerformed
        // TODO add your handling code here:
        if(admHospital.getTecnicos().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum Enfermeiro Cadastrado!");
        } else {
            new TelaListaTecnico(admHospital).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_listaTecnicosActionPerformed

    private void novoFarmaceuticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoFarmaceuticoActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarPessoa(admHospital, 4).setVisible(true);
        dispose();
    }//GEN-LAST:event_novoFarmaceuticoActionPerformed

    private void listaFarmaceuticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaFarmaceuticosActionPerformed
        // TODO add your handling code here:
        if(admHospital.getFarmaceuticos().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum Farmacêutico Cadastrado!");
        } else {
            new TelaListaFarmaceuticos(admHospital).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_listaFarmaceuticosActionPerformed

    private void infoAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoAdmActionPerformed
        // TODO add your handling code here:
        new TelaInformacoesAdministrador(admHospital).setVisible(true);
        dispose();
    }//GEN-LAST:event_infoAdmActionPerformed

    private void solicitacoesCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitacoesCadastroActionPerformed
        // TODO add your handling code here:
        new TelaAprovacaoPaciente(admHospital).setVisible(true);
        dispose();
    }//GEN-LAST:event_solicitacoesCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarDadosEnfermeiro;
    private javax.swing.JMenuItem alterarDadosFarmaceutico;
    private javax.swing.JMenuItem alterarDadosMedico;
    private javax.swing.JMenuItem alterarDadosTecnico;
    private javax.swing.JMenuItem alterarEstoque;
    private javax.swing.JMenuItem alterarLeito;
    private javax.swing.JMenuItem alterarStatus;
    private javax.swing.JMenu buscarMedicos;
    private javax.swing.JMenuItem cadastrarLeito;
    private javax.swing.JMenuItem dataAdmissaoMedico;
    private javax.swing.JMenu enfermeiros;
    private javax.swing.JMenuItem especialidadeMedico;
    private javax.swing.JMenu farmaceuticos;
    private javax.swing.JMenu gerenciar;
    private javax.swing.JMenuItem infoAdm;
    private javax.swing.JMenu internacoes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu leitos;
    private javax.swing.JMenuItem listaEnfermeiros;
    private javax.swing.JMenuItem listaFarmaceuticos;
    private javax.swing.JMenuItem listaMedicos;
    private javax.swing.JMenuItem listaTecnicos;
    private javax.swing.JMenu medicos;
    private javax.swing.JMenuItem novoEnfermeiro;
    private javax.swing.JMenuItem novoFarmaceutico;
    private javax.swing.JMenuItem novoMedico;
    private javax.swing.JMenuItem novoSuprimento;
    private javax.swing.JMenuItem novoTecnico;
    private javax.swing.JMenu pacientes;
    private javax.swing.JMenu recursosHumanos;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem solicitacoesCadastro;
    private javax.swing.JMenu suprimentos;
    private javax.swing.JMenu tecnicos;
    private javax.swing.JMenuItem verificarInternacoes;
    private javax.swing.JMenuItem verificarLeitos;
    private javax.swing.JMenuItem verificarPacientes;
    private javax.swing.JMenuItem verificarSuprimentos;
    // End of variables declaration//GEN-END:variables
}
