/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.Leito;
import classes.Suprimento;
import enums.DisponibilidadeLeito;
import enums.TipoLeito;
import enums.TipoSuprimento;
import gerenciamento.GerenciamentoHospitalar;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amanda
 */
public class TelaCadastroLeito extends javax.swing.JFrame {

    GerenciamentoHospitalar admHospital;
    ArrayList<Leito> listaLeitos;
    DefaultTableModel todosLeitos;
    /**
     * Creates new form TelaInicialAdministrador
     */
    public TelaCadastroLeito(GerenciamentoHospitalar admHospital) {
        initComponents();
        this.admHospital = admHospital;
        this.setLocationRelativeTo(null);
        this.listaLeitos = this.admHospital.getLeitos();
        todosLeitos = (DefaultTableModel) tabelaLeitos.getModel();
        todosLeitos.addColumn("Número do Leito");
        todosLeitos.addColumn("Tipo");
        todosLeitos.addColumn("Capacidade");
        todosLeitos.addColumn("Valor");
        todosLeitos.addColumn("Status");
        todosLeitos.addColumn("Observações");
        
        
        if(!this.listaLeitos.isEmpty()){
            preencheTabelaLeitos();
            desativarLimparCampos();
        } else {
            buscar.setEnabled(false);
        }
        
        preencheTipoLeito();
        preencheTipoDisponibilidade();
    }
    
    private void preencheTipoLeito(){
        listaTipoLeito.removeAllItems();
        for(TipoLeito l : TipoLeito.values()){
            listaTipoLeito.addItem(l.getTipoLeito());
        }
    }
    
    private void preencheTipoDisponibilidade(){
        listaDisponibilidade.removeAllItems();
        for(DisponibilidadeLeito d : DisponibilidadeLeito.values()){
            listaDisponibilidade.addItem(d.getDisponibilidadeLeito());
        }
    }
    
    private void preencheTabelaLeitos(){
        for(Leito l : listaLeitos){
            todosLeitos.addRow(new Object[]{l.getNumero(), l.getTipo().getTipoLeito(),
                l.getCapacidade() + " paciente(s)", "R$ " + l.getValor(),
                l.getDisponibilidade().getDisponibilidadeLeito(), l.getObservacoes()});
        }
    }
    
    private void atualizaTabela(){
        todosLeitos.setRowCount(0);
        preencheTabelaLeitos();
    }
    
    private void desativarLimparCampos(){
        numeroLeito.setText("");
        preencheTipoLeito();
        listaTipoLeito.setEnabled(false);
        capacidadeQuarto.setText("");
        capacidadeQuarto.setEnabled(false);
        valorLeito.setText("");
        valorLeito.setEnabled(false);
        preencheTipoDisponibilidade();
        listaDisponibilidade.setEnabled(false);
        observacoes.setText("");
        observacoes.setEnabled(false);
        cadastrar.setEnabled(false);
        buscar.setEnabled(true);
    }
    
    private void ativaCamposCadastro(){
        listaTipoLeito.setEnabled(true);
        capacidadeQuarto.setText("");
        capacidadeQuarto.setEnabled(true);
        valorLeito.setText("");
        valorLeito.setEnabled(true);
        listaDisponibilidade.setEnabled(true);
        observacoes.setText("");
        observacoes.setEnabled(true);
        cadastrar.setEnabled(true);
    }
    
    private void mostrarInformacoes(Leito leito){
        listaTipoLeito.setEnabled(true);
        int cont = 0;
        for(TipoLeito tl : TipoLeito.values()){
            if(leito.getTipo().equals(tl)){
                listaTipoLeito.setSelectedIndex(cont);
            }
            cont++;
        }
        listaTipoLeito.setEditable(false);
        capacidadeQuarto.setEnabled(true);
        capacidadeQuarto.setEditable(false);
        capacidadeQuarto.setText("" + leito.getCapacidade());
        valorLeito.setEnabled(true);
        valorLeito.setEditable(false);
        valorLeito.setText("" + leito.getValor());
        listaDisponibilidade.setEnabled(true);
        cont = 0;
        for(DisponibilidadeLeito dl : DisponibilidadeLeito.values()){
            if(leito.getDisponibilidade().equals(dl)){
                cont++;
            }
        }
        listaDisponibilidade.setEditable(false);
        observacoes.setEnabled(true);
        observacoes.setEditable(false);
        observacoes.setText(leito.getObservacoes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLeitos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        numeroLeito = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        listaTipoLeito = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        valorLeito = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        observacoes = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        voltar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        listaDisponibilidade = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        capacidadeQuarto = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();
        gerenciar = new javax.swing.JMenu();
        leitos = new javax.swing.JMenu();
        cadastrarLeito = new javax.swing.JMenuItem();
        alterarLeito = new javax.swing.JMenuItem();
        alterarStatus = new javax.swing.JMenuItem();
        verificarLeitos = new javax.swing.JMenuItem();
        suprimentos = new javax.swing.JMenu();
        novoSuprimento = new javax.swing.JMenuItem();
        alterarEstoque = new javax.swing.JMenuItem();
        verificarSuprimentos = new javax.swing.JMenuItem();
        internacoes = new javax.swing.JMenu();
        verificarInternacoes = new javax.swing.JMenuItem();
        recursosHumanos = new javax.swing.JMenu();
        medicos = new javax.swing.JMenu();
        novoMedico = new javax.swing.JMenuItem();
        alterarDadosMedico = new javax.swing.JMenuItem();
        listaMedicos = new javax.swing.JMenuItem();
        buscarMedicos = new javax.swing.JMenu();
        especialidadeMedico = new javax.swing.JMenuItem();
        dataAdmissaoMedico = new javax.swing.JMenuItem();
        enfermeiros = new javax.swing.JMenu();
        novoEnfermeiro = new javax.swing.JMenuItem();
        alterarDadosEnfermeiro = new javax.swing.JMenuItem();
        listaEnfermeiros = new javax.swing.JMenuItem();
        tecnicos = new javax.swing.JMenu();
        novoTecnico = new javax.swing.JMenuItem();
        alterarDadosTecnico = new javax.swing.JMenuItem();
        listaTecnicos = new javax.swing.JMenuItem();
        farmaceuticos = new javax.swing.JMenu();
        novoFarmaceutico = new javax.swing.JMenuItem();
        alterarDadosFarmaceutico = new javax.swing.JMenuItem();
        listaFarmaceuticos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Leito");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Leitos");

        tabelaLeitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaLeitos);

        jLabel2.setText("Número do Leito:");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo:");

        listaTipoLeito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Valor:");

        jLabel6.setText("Observações:");

        observacoes.setColumns(20);
        observacoes.setRows(5);
        jScrollPane2.setViewportView(observacoes);

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Disponibilidade:");

        listaDisponibilidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Capacidade do Quarto:");

        jMenu1.setText("Geral");

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu1.add(sair);

        jMenuBar1.add(jMenu1);

        gerenciar.setText("Gerenciamento Hospitalar");

        leitos.setText("Leitos");

        cadastrarLeito.setText("Cadastrar");
        cadastrarLeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLeitoActionPerformed(evt);
            }
        });
        leitos.add(cadastrarLeito);

        alterarLeito.setText("Alterar");
        leitos.add(alterarLeito);

        alterarStatus.setText("Alterar Status");
        alterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarStatusActionPerformed(evt);
            }
        });
        leitos.add(alterarStatus);

        verificarLeitos.setText("Verificar Leitos");
        leitos.add(verificarLeitos);

        gerenciar.add(leitos);

        suprimentos.setText("Suprimentos");

        novoSuprimento.setText("Cadastrar Novo Suprimento");
        novoSuprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoSuprimentoActionPerformed(evt);
            }
        });
        suprimentos.add(novoSuprimento);

        alterarEstoque.setText("Alterar Estoque");
        alterarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEstoqueActionPerformed(evt);
            }
        });
        suprimentos.add(alterarEstoque);

        verificarSuprimentos.setText("Verificar Suprimentos");
        suprimentos.add(verificarSuprimentos);

        gerenciar.add(suprimentos);

        internacoes.setText("Internações");

        verificarInternacoes.setText("Verificar Internações");
        internacoes.add(verificarInternacoes);

        gerenciar.add(internacoes);

        jMenuBar1.add(gerenciar);

        recursosHumanos.setText("Recursos Humanos");

        medicos.setText("Médicos");

        novoMedico.setText("Novo Médico");
        novoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoMedicoActionPerformed(evt);
            }
        });
        medicos.add(novoMedico);

        alterarDadosMedico.setText("Alterar Dados do Médico");
        medicos.add(alterarDadosMedico);

        listaMedicos.setText("Lista de Médicos");
        listaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMedicosActionPerformed(evt);
            }
        });
        medicos.add(listaMedicos);

        buscarMedicos.setText("Buscar Médicos");

        especialidadeMedico.setText("Por Especialidade");
        buscarMedicos.add(especialidadeMedico);

        dataAdmissaoMedico.setText("Por Data de Admisssão");
        dataAdmissaoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAdmissaoMedicoActionPerformed(evt);
            }
        });
        buscarMedicos.add(dataAdmissaoMedico);

        medicos.add(buscarMedicos);

        recursosHumanos.add(medicos);

        enfermeiros.setText("Enfermeiros");

        novoEnfermeiro.setText("Novo Enfermeiro");
        enfermeiros.add(novoEnfermeiro);

        alterarDadosEnfermeiro.setText("Alterar Dados do Enfermeiro");
        enfermeiros.add(alterarDadosEnfermeiro);

        listaEnfermeiros.setText("Lista de Enfermeiros");
        enfermeiros.add(listaEnfermeiros);

        recursosHumanos.add(enfermeiros);

        tecnicos.setText("Técnicos de Enfermagem");

        novoTecnico.setText("Novo Técnico");
        tecnicos.add(novoTecnico);

        alterarDadosTecnico.setText("Alterar Dados do Técnico");
        tecnicos.add(alterarDadosTecnico);

        listaTecnicos.setText("Lista de Técnicos");
        tecnicos.add(listaTecnicos);

        recursosHumanos.add(tecnicos);

        farmaceuticos.setText("Farmacêuticos");

        novoFarmaceutico.setText("Novo Farmacêutico");
        farmaceuticos.add(novoFarmaceutico);

        alterarDadosFarmaceutico.setText("Alterar Dados do Farmacêutico");
        farmaceuticos.add(alterarDadosFarmaceutico);

        listaFarmaceuticos.setText("Lista de Farmacêuticos");
        farmaceuticos.add(listaFarmaceuticos);

        recursosHumanos.add(farmaceuticos);

        jMenuBar1.add(recursosHumanos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroLeito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listaTipoLeito, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(capacidadeQuarto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valorLeito, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(voltar)
                        .addGap(381, 381, 381))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cadastrar)
                        .addGap(373, 373, 373))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numeroLeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(listaTipoLeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(capacidadeQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valorLeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(listaDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cadastrar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(voltar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sairMouseClicked

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void alterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarStatusActionPerformed

    private void novoSuprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoSuprimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoSuprimentoActionPerformed

    private void alterarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarEstoqueActionPerformed

    private void dataAdmissaoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAdmissaoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAdmissaoMedicoActionPerformed

    private void cadastrarLeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLeitoActionPerformed
        // TODO add your handling code here:
        new TelaCadastroLeito(admHospital).setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarLeitoActionPerformed

    private void novoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoMedicoActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarPessoa(admHospital, 1).setVisible(true);
        dispose();
    }//GEN-LAST:event_novoMedicoActionPerformed

    private void listaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMedicosActionPerformed
        // TODO add your handling code here:
        if(admHospital.getLeitos().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum Médico Cadastrado!");
        } else {
            new TelaListaMedicos(admHospital).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_listaMedicosActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        new TelaInicialAdministrador(admHospital).setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
        
        //Pega todas as informações do Leito;
        TipoLeito tipo = null;
        for(TipoLeito tl : TipoLeito.values()){
            if(listaTipoLeito.getSelectedItem().toString().equals(tl.getTipoLeito())){
                tipo = tl;
            }
        }
        DisponibilidadeLeito disponibilidade = null;
        for(DisponibilidadeLeito dl : DisponibilidadeLeito.values()){
            if(listaDisponibilidade.getSelectedItem().toString().equals(dl.getDisponibilidadeLeito())){
                disponibilidade = dl;
            }
        }
        int numero = Integer.parseInt(numeroLeito.getText());
        int capacidade = Integer.parseInt(capacidadeQuarto.getText());
        Double valor = Double.valueOf(valorLeito.getText());
        String observacao = observacoes.getText();
        
        //Cria o Objeto Leito
        Leito leito = new Leito();
        leito.setNumero(numero);
        leito.setTipo(tipo);
        leito.setCapacidade(capacidade);
        leito.setValor(valor);
        leito.setDisponibilidade(disponibilidade);
        leito.setObservacoes(observacao);
        
        
        //Retorna Objeto Leito com ID
        leito = admHospital.retornaLeitoComID(leito);
        
        //Cadastra Leito no Sistema
        boolean cadastro = admHospital.cadastrarLeito(leito);
        if(cadastro){
            //Atualiza Tabela de Leito
            atualizaTabela();
            desativarLimparCampos();
            JOptionPane.showMessageDialog(null, "Leito Cadastrado!");
        } else {
            JOptionPane.showMessageDialog(null, "Algo deu Errado!");
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        
        //Pegar o número do quarto pra busca
        int numero = Integer.parseInt(numeroLeito.getText());
        
        //Busca Leito
        Leito leito = admHospital.buscarLeitoPorNumero(numero);
        
        //Verifica se o Leito existe ou não
        if(leito.getNumero() == 0){
            JOptionPane.showMessageDialog(null, "Leito não encontrado. Sistema liberado pra cadastro.");
            ativaCamposCadastro();
        } else {
            JOptionPane.showMessageDialog(null, "Leito localizado.");
            mostrarInformacoes(leito);
        }
    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarDadosEnfermeiro;
    private javax.swing.JMenuItem alterarDadosFarmaceutico;
    private javax.swing.JMenuItem alterarDadosMedico;
    private javax.swing.JMenuItem alterarDadosTecnico;
    private javax.swing.JMenuItem alterarEstoque;
    private javax.swing.JMenuItem alterarLeito;
    private javax.swing.JMenuItem alterarStatus;
    private javax.swing.JButton buscar;
    private javax.swing.JMenu buscarMedicos;
    private javax.swing.JButton cadastrar;
    private javax.swing.JMenuItem cadastrarLeito;
    private javax.swing.JTextField capacidadeQuarto;
    private javax.swing.JMenuItem dataAdmissaoMedico;
    private javax.swing.JMenu enfermeiros;
    private javax.swing.JMenuItem especialidadeMedico;
    private javax.swing.JMenu farmaceuticos;
    private javax.swing.JMenu gerenciar;
    private javax.swing.JMenu internacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu leitos;
    private javax.swing.JComboBox<String> listaDisponibilidade;
    private javax.swing.JMenuItem listaEnfermeiros;
    private javax.swing.JMenuItem listaFarmaceuticos;
    private javax.swing.JMenuItem listaMedicos;
    private javax.swing.JMenuItem listaTecnicos;
    private javax.swing.JComboBox<String> listaTipoLeito;
    private javax.swing.JMenu medicos;
    private javax.swing.JMenuItem novoEnfermeiro;
    private javax.swing.JMenuItem novoFarmaceutico;
    private javax.swing.JMenuItem novoMedico;
    private javax.swing.JMenuItem novoSuprimento;
    private javax.swing.JMenuItem novoTecnico;
    private javax.swing.JTextField numeroLeito;
    private javax.swing.JTextArea observacoes;
    private javax.swing.JMenu recursosHumanos;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenu suprimentos;
    private javax.swing.JTable tabelaLeitos;
    private javax.swing.JMenu tecnicos;
    private javax.swing.JFormattedTextField valorLeito;
    private javax.swing.JMenuItem verificarInternacoes;
    private javax.swing.JMenuItem verificarLeitos;
    private javax.swing.JMenuItem verificarSuprimentos;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
