/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.Anamnese;
import classes.AnamneseFeminina;
import enums.CicloMenstrual;
import enums.Sexo;
import enums.TipoAnticoncepcional;
import gerenciamento.GerenciamentoPaciente;
import javax.swing.JOptionPane;

/**
 *
 * @author Amanda
 */
public class TelaAnamneseCliente extends javax.swing.JFrame {

    GerenciamentoPaciente gerenciamentoPaciente;
    /**
     * Creates new form TelaInicialAdministrador
     */
    public TelaAnamneseCliente(GerenciamentoPaciente gerenciamentoPaciente){
        initComponents();
        this.setLocationRelativeTo(null);
        this.gerenciamentoPaciente = gerenciamentoPaciente;
        preencheListaCiclo();
        preencheListaAnticoncepcional();
        desativacaoCampos();
        if(gerenciamentoPaciente.retornaSexo().equals(Sexo.M)){
            listaCiclo.setEnabled(false);
            usoAnticoncepcional.setEnabled(false);
            listaAnticoncepcional.setEnabled(false);
        }
    }
    
    
    private void preencheListaCiclo(){
        listaCiclo.removeAllItems();
        for(CicloMenstrual cm : CicloMenstrual.values()){
            listaCiclo.addItem(cm.getCicloMenstrual());
        }
    }
    
    private void preencheListaAnticoncepcional(){
        listaAnticoncepcional.removeAllItems();
        for(TipoAnticoncepcional ta : TipoAnticoncepcional.values()){
            listaAnticoncepcional.addItem(ta.getTipoAnticoncepcional());
        }
    }
    
    private void desativacaoCampos(){
        anotacoesRespiratorios.setEnabled(false);
        anotacoesCirurgias.setEnabled(false);
        exerciciosDias.setEnabled(false);
        bebidaDias.setEnabled(false);
        anotacoesAlergias.setEnabled(false);
        anotacoesAlimentos.setEnabled(false);
        descricaoTratamentoAtual.setEnabled(false);
        descricaoMedicacoes.setEnabled(false);
        listaAnticoncepcional.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        diabetes = new javax.swing.JCheckBox();
        hipertensao = new javax.swing.JCheckBox();
        hipotensao = new javax.swing.JCheckBox();
        tabagismo = new javax.swing.JCheckBox();
        epilepsia = new javax.swing.JCheckBox();
        proteseDentaria = new javax.swing.JCheckBox();
        problemasRespiratorios = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        anotacoesRespiratorios = new javax.swing.JTextField();
        cirurgias = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        anotacoesCirurgias = new javax.swing.JTextField();
        exerciciosFisicos = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        exerciciosDias = new javax.swing.JTextField();
        alcool = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        bebidaDias = new javax.swing.JTextField();
        alergiaMedicamento = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        anotacoesAlergias = new javax.swing.JTextField();
        alergiaAlimentos = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        anotacoesAlimentos = new javax.swing.JTextField();
        tratamentoAtual = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoTratamentoAtual = new javax.swing.JTextArea();
        marcaPasso = new javax.swing.JCheckBox();
        medicacaoContinuo = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricaoMedicacoes = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        listaCiclo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        usoAnticoncepcional = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        listaAnticoncepcional = new javax.swing.JComboBox<>();
        salvar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        sair = new javax.swing.JMenu();
        consultas = new javax.swing.JMenu();
        meusDados = new javax.swing.JMenu();
        anamnese = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Anamnese");

        jLabel2.setText("Por favor, responda de forma correta para que isso facilite em suas consultas. Quanto mais informações, melhor.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Selecione as opções que você tem:");

        diabetes.setText("Diabetes");

        hipertensao.setText("Hipertensão");

        hipotensao.setText("Hipotensão");

        tabagismo.setText("Tabagismo");

        epilepsia.setText("Epilepsia");

        proteseDentaria.setText("Prótese Dentária");

        problemasRespiratorios.setText("Problemas Respiratórios");
        problemasRespiratorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problemasRespiratoriosActionPerformed(evt);
            }
        });

        jLabel4.setText("Se sim, descreva quais:");

        cirurgias.setText("Cirurgias");
        cirurgias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cirurgiasActionPerformed(evt);
            }
        });

        jLabel5.setText("Se sim, descreva quais:");

        exerciciosFisicos.setText("Exercícios Físicos");
        exerciciosFisicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exerciciosFisicosActionPerformed(evt);
            }
        });

        jLabel6.setText("Quantas vezes por semana:");

        alcool.setText("Álcool");
        alcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alcoolActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantas vezes por semana:");

        alergiaMedicamento.setText("Alergia a Medicamento(s)");
        alergiaMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergiaMedicamentoActionPerformed(evt);
            }
        });

        jLabel8.setText("Se sim, descreva quais:");

        alergiaAlimentos.setText("Alergia a Alimentos");
        alergiaAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergiaAlimentosActionPerformed(evt);
            }
        });

        jLabel9.setText("Se sim, descreva quais:");

        tratamentoAtual.setText("Algum tratamento atual?");
        tratamentoAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratamentoAtualActionPerformed(evt);
            }
        });

        jLabel10.setText("Se sim, descreva sobre ele:");

        descricaoTratamentoAtual.setColumns(20);
        descricaoTratamentoAtual.setRows(5);
        jScrollPane1.setViewportView(descricaoTratamentoAtual);

        marcaPasso.setText("Utiliza Marca Passo?");

        medicacaoContinuo.setText("Utiliza Medicação de uso Contínuo?");
        medicacaoContinuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicacaoContinuoActionPerformed(evt);
            }
        });

        jLabel11.setText("Se Sim, qual(is)?");

        descricaoMedicacoes.setColumns(20);
        descricaoMedicacoes.setRows(5);
        jScrollPane2.setViewportView(descricaoMedicacoes);

        jLabel12.setText("Ciclo Menstrual: ");

        listaCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setText("Usa Anticoncepcional:");

        usoAnticoncepcional.setText("Sim");
        usoAnticoncepcional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usoAnticoncepcionalActionPerformed(evt);
            }
        });

        jLabel14.setText("Se sim, qual?");

        listaAnticoncepcional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenuBar2.add(sair);

        consultas.setText("Consultas");
        jMenuBar2.add(consultas);

        meusDados.setText("Meus Dados");
        meusDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meusDadosActionPerformed(evt);
            }
        });

        anamnese.setText("Anamnese");
        anamnese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamneseActionPerformed(evt);
            }
        });
        meusDados.add(anamnese);

        jMenuBar2.add(meusDados);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alcool, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exerciciosFisicos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exerciciosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bebidaDias)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(marcaPasso)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usoAnticoncepcional)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaAnticoncepcional, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(medicacaoContinuo)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tratamentoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(alergiaMedicamento)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anotacoesAlergias))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cirurgias, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anotacoesCirurgias))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(problemasRespiratorios, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anotacoesRespiratorios))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(diabetes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tabagismo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(150, 150, 150)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hipertensao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(epilepsia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(150, 150, 150)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(proteseDentaria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hipotensao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 150, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(alergiaAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anotacoesAlimentos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diabetes)
                    .addComponent(hipertensao)
                    .addComponent(hipotensao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabagismo)
                    .addComponent(epilepsia)
                    .addComponent(proteseDentaria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(problemasRespiratorios)
                    .addComponent(jLabel4)
                    .addComponent(anotacoesRespiratorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cirurgias)
                    .addComponent(jLabel5)
                    .addComponent(anotacoesCirurgias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exerciciosFisicos)
                        .addGap(18, 18, 18)
                        .addComponent(alcool))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(exerciciosDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(bebidaDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergiaMedicamento)
                    .addComponent(jLabel8)
                    .addComponent(anotacoesAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergiaAlimentos)
                    .addComponent(jLabel9)
                    .addComponent(anotacoesAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tratamentoAtual)
                        .addComponent(jLabel10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(marcaPasso)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(medicacaoContinuo)
                        .addComponent(jLabel11))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(listaCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(usoAnticoncepcional)
                    .addComponent(jLabel14)
                    .addComponent(listaAnticoncepcional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar)
                    .addComponent(voltar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void meusDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meusDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meusDadosActionPerformed

    private void anamneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamneseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anamneseActionPerformed

    private void cirurgiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cirurgiasActionPerformed
        // TODO add your handling code here:
        anotacoesCirurgias.setEnabled(cirurgias.isSelected());
    }//GEN-LAST:event_cirurgiasActionPerformed

    private void alcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alcoolActionPerformed
        // TODO add your handling code here:
        bebidaDias.setEnabled(alcool.isSelected());
    }//GEN-LAST:event_alcoolActionPerformed

    private void alergiaAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergiaAlimentosActionPerformed
        // TODO add your handling code here:
        anotacoesAlimentos.setEnabled(alergiaAlimentos.isSelected());
    }//GEN-LAST:event_alergiaAlimentosActionPerformed

    private void problemasRespiratoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problemasRespiratoriosActionPerformed
        // TODO add your handling code here:
        anotacoesRespiratorios.setEnabled(problemasRespiratorios.isSelected());
    }//GEN-LAST:event_problemasRespiratoriosActionPerformed

    private void exerciciosFisicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exerciciosFisicosActionPerformed
        // TODO add your handling code here:
        exerciciosDias.setEnabled(exerciciosFisicos.isSelected());
    }//GEN-LAST:event_exerciciosFisicosActionPerformed

    private void alergiaMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergiaMedicamentoActionPerformed
        // TODO add your handling code here:
        anotacoesAlergias.setEnabled(alergiaMedicamento.isSelected());
    }//GEN-LAST:event_alergiaMedicamentoActionPerformed

    private void tratamentoAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratamentoAtualActionPerformed
        // TODO add your handling code here:
        descricaoTratamentoAtual.setEnabled(tratamentoAtual.isSelected());
    }//GEN-LAST:event_tratamentoAtualActionPerformed

    private void medicacaoContinuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicacaoContinuoActionPerformed
        // TODO add your handling code here:
        descricaoMedicacoes.setEnabled(medicacaoContinuo.isSelected());
    }//GEN-LAST:event_medicacaoContinuoActionPerformed

    private void usoAnticoncepcionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usoAnticoncepcionalActionPerformed
        // TODO add your handling code here:
        listaAnticoncepcional.setEnabled(usoAnticoncepcional.isSelected());
    }//GEN-LAST:event_usoAnticoncepcionalActionPerformed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairMouseClicked

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        new TelaInicialPaciente(gerenciamentoPaciente).setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        Anamnese anamnese = new Anamnese();
        anamnese.setId(1);
        anamnese.setDiabetes(diabetes.isSelected());
        anamnese.setHipertensao(hipertensao.isSelected());
        anamnese.setHipotensao(hipotensao.isSelected());
        anamnese.setTabagismo(tabagismo.isSelected());
        anamnese.setEpilepsia(epilepsia.isSelected());
        anamnese.setProteseDentaria(proteseDentaria.isSelected());
        anamnese.setProblemasRespiratorios(problemasRespiratorios.isSelected());
        if(problemasRespiratorios.isSelected()){
            anamnese.setAnotacoesProblemasRespiratorios(anotacoesRespiratorios.getText());
        }
        anamnese.setCirurgias(cirurgias.isSelected());
        if(cirurgias.isSelected()){
            anamnese.setAnotacoesCirurgias(anotacoesCirurgias.getText());
        }
        anamnese.setExerciciosFisicos(exerciciosFisicos.isSelected());
        if(exerciciosFisicos.isSelected()){
            anamnese.setFrequenciaExercicios(Integer.parseInt(exerciciosDias.getText()));
        } else {
            anamnese.setFrequenciaExercicios(-1);
        }
        anamnese.setAlcool(alcool.isSelected());
        if(alcool.isSelected()){
            anamnese.setFrequenciaAlcool(Integer.parseInt(bebidaDias.getText()));
        } else {
            anamnese.setFrequenciaAlcool(-1);
        }
        anamnese.setAlergiaMedicacao(alergiaMedicamento.isSelected());
        if(alergiaMedicamento.isSelected()){
            anamnese.setAnotacoesAlergiaMedicacao(anotacoesAlergias.getText());
        }
        anamnese.setAlergiaAlimento(alergiaAlimentos.isSelected());
        if(alergiaAlimentos.isSelected()){
            anamnese.setAnotacoesAlergiaAlimento(anotacoesAlergias.getText());
        }
        anamnese.setTratamentoMedicoAtual(tratamentoAtual.isSelected());
        if(tratamentoAtual.isSelected()){
            anamnese.setAnotacoesTratamento(descricaoTratamentoAtual.getText());
        }
        anamnese.setMarcaPasso(marcaPasso.isSelected());
        anamnese.setMedicamentoContinuo(medicacaoContinuo.isSelected());
        if(medicacaoContinuo.isSelected()){
            anamnese.setAnotacoesMedicamentoContinuo(descricaoMedicacoes.getText());
        }
        
        boolean anticoncepcional = false;
        TipoAnticoncepcional tipo = TipoAnticoncepcional.UM;
        CicloMenstrual ciclo = CicloMenstrual.UM;
        if(gerenciamentoPaciente.retornaSexo().equals(Sexo.F)){
            anticoncepcional = usoAnticoncepcional.isSelected();
            if(usoAnticoncepcional.isSelected()){
                for(TipoAnticoncepcional ta : TipoAnticoncepcional.values()){
                    if(listaAnticoncepcional.getSelectedItem().toString().equals(ta.getTipoAnticoncepcional())){
                        tipo = ta;
                    }
                }
            }
            for(CicloMenstrual cm : CicloMenstrual.values()){
                if(listaCiclo.getSelectedItem().toString().equals(cm.getCicloMenstrual())){
                    ciclo = cm;
                }
            }
            AnamneseFeminina anamneseFeminina = new AnamneseFeminina(anticoncepcional, tipo, ciclo,
                    anamnese.getId(), anamnese.isDiabetes(), anamnese.isHipertensao(), anamnese.isHipotensao(),
                    anamnese.isTabagismo(), anamnese.isEpilepsia(), anamnese.isProteseDentaria(),
                    anamnese.isProblemasRespiratorios(), anamnese.getAnotacoesProblemasRespiratorios(),
                    anamnese.isCirurgias(), anamnese.getAnotacoesCirurgias(), anamnese.isExerciciosFisicos(),
                    anamnese.getFrequenciaExercicios(), anamnese.isAlcool(), anamnese.getFrequenciaAlcool(),
                    anamnese.isAlergiaMedicacao(), anamnese.getAnotacoesAlergiaMedicacao(), anamnese.isAlergiaAlimento(),
                    anamnese.getAnotacoesAlergiaAlimento(), anamnese.isTratamentoMedicoAtual(), anamnese.getAnotacoesTratamento(),
                    anamnese.isMarcaPasso(), anamnese.isMedicamentoContinuo(), anamnese.getAnotacoesMedicamentoContinuo());
            
            if(gerenciamentoPaciente.novaAnamnese(anamneseFeminina)){
                JOptionPane.showMessageDialog(null, "Anamnese realizada!\n Obrigada por responder as perguntas.");
            }
        } else {
            if(gerenciamentoPaciente.novaAnamnese(anamnese)){
                JOptionPane.showMessageDialog(null, "Anamnese realizada!\n Obrigada por responder as perguntas.");
            }
        }
        
        new TelaInicialPaciente(gerenciamentoPaciente).setVisible(true);
        dispose();
    }//GEN-LAST:event_salvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alcool;
    private javax.swing.JCheckBox alergiaAlimentos;
    private javax.swing.JCheckBox alergiaMedicamento;
    private javax.swing.JMenuItem anamnese;
    private javax.swing.JTextField anotacoesAlergias;
    private javax.swing.JTextField anotacoesAlimentos;
    private javax.swing.JTextField anotacoesCirurgias;
    private javax.swing.JTextField anotacoesRespiratorios;
    private javax.swing.JTextField bebidaDias;
    private javax.swing.JCheckBox cirurgias;
    private javax.swing.JMenu consultas;
    private javax.swing.JTextArea descricaoMedicacoes;
    private javax.swing.JTextArea descricaoTratamentoAtual;
    private javax.swing.JCheckBox diabetes;
    private javax.swing.JCheckBox epilepsia;
    private javax.swing.JTextField exerciciosDias;
    private javax.swing.JCheckBox exerciciosFisicos;
    private javax.swing.JCheckBox hipertensao;
    private javax.swing.JCheckBox hipotensao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> listaAnticoncepcional;
    private javax.swing.JComboBox<String> listaCiclo;
    private javax.swing.JCheckBox marcaPasso;
    private javax.swing.JCheckBox medicacaoContinuo;
    private javax.swing.JMenu meusDados;
    private javax.swing.JCheckBox problemasRespiratorios;
    private javax.swing.JCheckBox proteseDentaria;
    private javax.swing.JMenu sair;
    private javax.swing.JButton salvar;
    private javax.swing.JCheckBox tabagismo;
    private javax.swing.JCheckBox tratamentoAtual;
    private javax.swing.JCheckBox usoAnticoncepcional;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
