/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.Agenda;
import enums.Sexo;
import gerenciamento.GerenciamentoMedico;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amanda
 */
public class TelaInicialMedico extends javax.swing.JFrame {

    GerenciamentoMedico gerenciamentoMedico;
    DefaultTableModel listaConsultasDia;
    String dataConvertida;
    
    /**
     * Creates new form TelaInicialAdministrador
     */
    public TelaInicialMedico(GerenciamentoMedico agendaMedica){
        initComponents();
        this.setLocationRelativeTo(null);
        this.gerenciamentoMedico = agendaMedica;
        LocalDate hoje = LocalDate.now();
        DateTimeFormatter formataData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        dataConvertida = hoje.format(formataData);
        if(gerenciamentoMedico.getMedico().getSexo().equals(Sexo.F)){
            this.nomeDr.setText("Seja Bem-vinda Drª " + gerenciamentoMedico.getMedico().getNomeCompleto());
        } else {
            this.nomeDr.setText("Seja Bem-vindo Drº " + gerenciamentoMedico.getMedico().getNomeCompleto());
        }
        this.dataAtual.setText("Data: " + dataConvertida);
        
        listaConsultasDia = (DefaultTableModel) consultasDia.getModel();
        preencheTabela();
    }
    
    private void preencheTabela(){
        listaConsultasDia.setRowCount(0);
        ArrayList<Agenda> listaConsultas = gerenciamentoMedico.consultasDia(dataConvertida);
        if(listaConsultas.isEmpty()){
            if(!gerenciamentoMedico.isLoginCheck()){
                JOptionPane.showMessageDialog(null, "Olá Dr(a). " + gerenciamentoMedico.getMedico().getNomeCompleto()
                + "\nHoje não há consultas agendadas.");
                gerenciamentoMedico.setLoginCheck(true);
                iniciarConsulta.setEnabled(false);
            }
        } else {
            for(Agenda a : listaConsultas){
                listaConsultasDia.addRow(new Object[]{a.getHora(), "Teste " + a.getId()});
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        nomeDr = new javax.swing.JLabel();
        dataAtual = new javax.swing.JLabel();
        iniciarConsulta = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        consultasDia = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        sair = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        agendaCompleta = new javax.swing.JMenuItem();
        addNovasDatas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeDr.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nomeDr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomeDr.setText("Label Bem Vindo Dr.");

        dataAtual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dataAtual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dataAtual.setText("Label da Data Atual");

        iniciarConsulta.setText("Iniciar Consulta");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Consultas Agendadas do Dia");

        consultasDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Horário", "Paciente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        consultasDia.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(consultasDia);
        if (consultasDia.getColumnModel().getColumnCount() > 0) {
            consultasDia.getColumnModel().getColumn(0).setResizable(false);
            consultasDia.getColumnModel().getColumn(0).setPreferredWidth(10);
            consultasDia.getColumnModel().getColumn(1).setHeaderValue("Paciente");
        }

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenuBar2.add(sair);

        jMenu1.setText("Minha Agenda");

        agendaCompleta.setText("Agenda Completa");
        agendaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaCompletaActionPerformed(evt);
            }
        });
        jMenu1.add(agendaCompleta);

        addNovasDatas.setText("Adicionar Novas Datas");
        addNovasDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNovasDatasActionPerformed(evt);
            }
        });
        jMenu1.add(addNovasDatas);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Internações");

        jMenuItem2.setText("Nova Internação");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Gerenciar Internações");
        jMenu2.add(jMenuItem3);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeDr, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                                    .addComponent(dataAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(iniciarConsulta)))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(nomeDr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataAtual)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iniciarConsulta)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairMouseClicked

    private void addNovasDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNovasDatasActionPerformed
        // TODO add your handling code here:
        new TelaCadastroDatasConsultas(gerenciamentoMedico).setVisible(true);
        dispose();
    }//GEN-LAST:event_addNovasDatasActionPerformed

    private void agendaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaCompletaActionPerformed
        // TODO add your handling code here:
        new TelaAgendaCompletaMedico(gerenciamentoMedico).setVisible(true);
        dispose();
    }//GEN-LAST:event_agendaCompletaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addNovasDatas;
    private javax.swing.JMenuItem agendaCompleta;
    private javax.swing.JTable consultasDia;
    private javax.swing.JLabel dataAtual;
    private javax.swing.JButton iniciarConsulta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nomeDr;
    private javax.swing.JMenu sair;
    // End of variables declaration//GEN-END:variables
}
