/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.Login;
import classes.Medico;
import classes.Paciente;
import enums.TipoConta;
import gerenciamento.GerenciamentoHospitalar;
import gerenciamento.GerenciamentoMedico;
import gerenciamento.GerenciamentoPaciente;
import gerenciamento.GerenciarAgenda;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Amanda
 */
public class TelaInicial extends javax.swing.JFrame {

    GerenciamentoHospitalar admHospital;
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial(GerenciamentoHospitalar admHospital) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.admHospital = admHospital;
        this.admHospital.imprimiLogins();
    }
    
    private void usuarioParaCNPJ(){
        try{
            
            MaskFormatter mascaraCNPJ = new MaskFormatter("##.###.###/####-##");
            mascaraCNPJ.setValueContainsLiteralCharacters(false);
            usuario.setText(mascaraCNPJ.valueToString(usuario.getText()));
            
        }catch(Exception e){
            System.out.println("Erro ao converter CNPJ");
        }
    }
    
    private void usuarioParaCPF(){
        try{
            
            MaskFormatter mascaraCNPJ = new MaskFormatter("###.###.###-##");
            mascaraCNPJ.setValueContainsLiteralCharacters(false);
            usuario.setText(mascaraCNPJ.valueToString(usuario.getText()));
            
        }catch(Exception e){
            System.out.println("Erro ao converter CNPJ");
        }
    }
    
    private void limparCampos(){
        usuario.setText("");
        senha.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        novoPaciente = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vida Plus - SGHSS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bem-vindo! Realize o Login para continuar.");

        jLabel3.setText("Usuário:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Deseja ser nosso paciente? Clique em Cadastrar-se.");

        novoPaciente.setText("Cadastrar-se");
        novoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoPacienteActionPerformed(evt);
            }
        });

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 95, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(entrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usuario)
                                    .addComponent(senha, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(novoPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(entrar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(novoPaciente))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // TODO add your handling code here:
        char[] senhaConvertida = senha.getPassword();
        String senhaDigitada = new String(senhaConvertida);
        System.out.println("Digitado: " + usuario.getText() + " / " + senhaDigitada);
        switch (usuario.getText().length()) {
            case 14 -> {
                usuarioParaCNPJ();
                if(admHospital.verificaAcessoAdministracao(usuario.getText(), senhaDigitada)){
                    new TelaInicialAdministrador(admHospital).setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário/Senha incorretos. Por favor, tente novamente.");
                }
            }
            case 11 -> {
                usuarioParaCPF();
                Login login = admHospital.buscaLogin(usuario.getText(), senhaDigitada);
                System.out.println("Login Localizado: " + login);
                if(login == null){
                    JOptionPane.showMessageDialog(null, "Usuário/Senha incorretos. Por favor, tente novamente.");
                } else {
                    TipoConta conta = login.getTipoConta();
                    
                    switch (conta) {
                        case P -> {
                            Paciente paciente = admHospital.buscaPacientePorLogin(login.getId());
                            if(paciente != null){
                                new TelaInicialPaciente(new GerenciamentoPaciente(paciente, admHospital)).setVisible(true);
                                dispose();
                            } else {
                                JOptionPane.showMessageDialog(null, "Erro ao recuperar informações!");
                            }
                        }
                        case M -> {
                            Medico medico = admHospital.buscaMedicoPorLogin(login.getId());
                            if(medico != null){
                                new TelaInicialMedico(new GerenciamentoMedico(medico)).setVisible(true);
                                dispose();
                            } else {
                                JOptionPane.showMessageDialog(null, "Erro ao recuperar informações!");
                            }
                        }
                        default -> throw new AssertionError();
                    }
                }
            }
            default -> JOptionPane.showMessageDialog(null, "Quantidade de caracteres no usuário inesperado. Por favor,"
                        + "verifique e tente novamente.");
        }
        
        limparCampos();
    }//GEN-LAST:event_entrarActionPerformed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairMouseClicked

    private void novoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoPacienteActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarPaciente(admHospital).setVisible(true);
        dispose();
    }//GEN-LAST:event_novoPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton novoPaciente;
    private javax.swing.JMenu sair;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
