/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author Amanda
 */
public class TelaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdministrador
     */
    public TelaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();
        gerenciar = new javax.swing.JMenu();
        leitos = new javax.swing.JMenu();
        cadastrarLeito = new javax.swing.JMenuItem();
        alterarLeito = new javax.swing.JMenuItem();
        alterarStatus = new javax.swing.JMenuItem();
        verificarLeitos = new javax.swing.JMenuItem();
        suprimentos = new javax.swing.JMenu();
        novoSuprimento = new javax.swing.JMenuItem();
        alterarEstoque = new javax.swing.JMenuItem();
        verificarSuprimentos = new javax.swing.JMenuItem();
        internacoes = new javax.swing.JMenu();
        verificarInternacoes = new javax.swing.JMenuItem();
        recursosHumanos = new javax.swing.JMenu();
        medicos = new javax.swing.JMenu();
        novoMedico = new javax.swing.JMenuItem();
        alterarDadosMedico = new javax.swing.JMenuItem();
        listaMedicos = new javax.swing.JMenuItem();
        buscarMedicos = new javax.swing.JMenu();
        especialidadeMedico = new javax.swing.JMenuItem();
        dataAdmissaoMedico = new javax.swing.JMenuItem();
        enfermeiros = new javax.swing.JMenu();
        tecnicos = new javax.swing.JMenu();
        farmaceuticos = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Geral");

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu1.add(sair);

        jMenuBar1.add(jMenu1);

        gerenciar.setText("Gerenciamento Hospitalar");

        leitos.setText("Leitos");

        cadastrarLeito.setText("Cadastrar");
        leitos.add(cadastrarLeito);

        alterarLeito.setText("Alterar");
        leitos.add(alterarLeito);

        alterarStatus.setText("Alterar Status");
        alterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarStatusActionPerformed(evt);
            }
        });
        leitos.add(alterarStatus);

        verificarLeitos.setText("Verificar Leitos");
        leitos.add(verificarLeitos);

        gerenciar.add(leitos);

        suprimentos.setText("Suprimentos");

        novoSuprimento.setText("Cadastrar Novo Suprimento");
        novoSuprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoSuprimentoActionPerformed(evt);
            }
        });
        suprimentos.add(novoSuprimento);

        alterarEstoque.setText("Alterar Estoque");
        alterarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEstoqueActionPerformed(evt);
            }
        });
        suprimentos.add(alterarEstoque);

        verificarSuprimentos.setText("Verificar Suprimentos");
        suprimentos.add(verificarSuprimentos);

        gerenciar.add(suprimentos);

        internacoes.setText("Internações");

        verificarInternacoes.setText("Verificar Internações");
        internacoes.add(verificarInternacoes);

        gerenciar.add(internacoes);

        jMenuBar1.add(gerenciar);

        recursosHumanos.setText("Recursos Humanos");

        medicos.setText("Médicos");

        novoMedico.setText("Novo Médico");
        medicos.add(novoMedico);

        alterarDadosMedico.setText("Alterar Dados do Médico");
        medicos.add(alterarDadosMedico);

        listaMedicos.setText("Lista de Médicos");
        medicos.add(listaMedicos);

        buscarMedicos.setText("Buscar Médicos");

        especialidadeMedico.setText("Por Especialidade");
        buscarMedicos.add(especialidadeMedico);

        dataAdmissaoMedico.setText("Por Data de Admisssão");
        dataAdmissaoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAdmissaoMedicoActionPerformed(evt);
            }
        });
        buscarMedicos.add(dataAdmissaoMedico);

        medicos.add(buscarMedicos);

        recursosHumanos.add(medicos);

        enfermeiros.setText("Enfermeiros");
        recursosHumanos.add(enfermeiros);

        tecnicos.setText("Técnicos de Enfermagem");
        recursosHumanos.add(tecnicos);

        farmaceuticos.setText("Farmaceuticos");
        recursosHumanos.add(farmaceuticos);

        jMenuBar1.add(recursosHumanos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sairMouseClicked

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void alterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarStatusActionPerformed

    private void novoSuprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoSuprimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoSuprimentoActionPerformed

    private void alterarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarEstoqueActionPerformed

    private void dataAdmissaoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAdmissaoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAdmissaoMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarDadosMedico;
    private javax.swing.JMenuItem alterarEstoque;
    private javax.swing.JMenuItem alterarLeito;
    private javax.swing.JMenuItem alterarStatus;
    private javax.swing.JMenu buscarMedicos;
    private javax.swing.JMenuItem cadastrarLeito;
    private javax.swing.JMenuItem dataAdmissaoMedico;
    private javax.swing.JMenu enfermeiros;
    private javax.swing.JMenuItem especialidadeMedico;
    private javax.swing.JMenu farmaceuticos;
    private javax.swing.JMenu gerenciar;
    private javax.swing.JMenu internacoes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu leitos;
    private javax.swing.JMenuItem listaMedicos;
    private javax.swing.JMenu medicos;
    private javax.swing.JMenuItem novoMedico;
    private javax.swing.JMenuItem novoSuprimento;
    private javax.swing.JMenu recursosHumanos;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenu suprimentos;
    private javax.swing.JMenu tecnicos;
    private javax.swing.JMenuItem verificarInternacoes;
    private javax.swing.JMenuItem verificarLeitos;
    private javax.swing.JMenuItem verificarSuprimentos;
    // End of variables declaration//GEN-END:variables
}
